name: Central Deploy Pipeline

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      ecr-repo:
        required: true
        type: string
      helm-repo:
        required: true
        type: string
      eks-cluster:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCOUNT_ID:
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com

      - name: Build & Push Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ inputs.ecr-repo }}:$IMAGE_TAG .
          docker tag ${{ inputs.ecr-repo }}:$IMAGE_TAG \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo }}:$IMAGE_TAG
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo }}:$IMAGE_TAG

      - name: Push Helm Chart
        run: |
          helm package helm/demo-api
          aws ecr get-login-password | \
          helm registry login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
          helm push demo-api-0.1.0.tgz \
          oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.helm-repo }}

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --region ${{ inputs.aws-region }} --name ${{ inputs.eks-cluster }}
          helm upgrade --install demo-api \
          oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.helm-repo }}/demo-api \
          --version 0.1.0 \
          --set image.tag=${{ github.sha }}
